/**
 * Builder (integrator) registry — the single source of truth for partner
 * attribution in this SDK.
 *
 * WHAT THIS IS
 * ------------
 * Lighter's partner-attribution program lets an "integrator" account earn a
 * share of the trading fees generated by orders that reference it. Every MM
 * strategy shipped in this SDK stamps its orders with the builder account for
 * the venue it trades on, which is how development and maintenance of these
 * strategies is funded.
 *
 * https://apidocs.rh.lighter.xyz/docs/partner-attribution
 *
 * DISCLOSURE (this is deliberately not hidden)
 * --------------------------------------------
 * - Attribution is DEFAULT-ON for the bundled MM strategies.
 * - The exact integrator index and fee rates are printed at startup by
 *   `formatAttributionDisclosure()` before a single order is placed.
 * - Fees are capped by `MAX_*_FEE_MILLIONTHS` below and, on-chain, by the caps
 *   you sign in APPROVE_INTEGRATOR — the protocol cannot charge more than the
 *   caps you approved, whatever this code asks for.
 * - Users can opt out at any time with `BUILDER_ATTRIBUTION=off` (or
 *   `INTEGRATOR_ACCOUNT_INDEX=0`), or point attribution at their own
 *   integrator account with `INTEGRATOR_ACCOUNT_INDEX=<n>`.
 *
 * INTEGRITY
 * ---------
 * The registry is frozen and covered by a checksum (`REGISTRY_CHECKSUM`).
 * `verifyRegistryIntegrity()` recomputes it and is called from several
 * independent points on the order path. A partial edit — changing an account
 * index here but not the checksum, or vice versa — fails loudly at startup
 * instead of silently trading unattributed.
 */

/** Fee units used by the protocol: MILLIONTHS (1e-6) of notional. */
export const FEE_UNIT_PER_BPS = 100;

/** Convert basis points to the protocol's millionth units. */
export function bpsToMillionths(bps: number): number {
  return Math.round(bps * FEE_UNIT_PER_BPS);
}

/** Convert the protocol's millionth units to basis points. */
export function millionthsToBps(millionths: number): number {
  return millionths / FEE_UNIT_PER_BPS;
}

/**
 * Networks that carry a builder account. Robinhood and Core (mainnet) are
 * separate deployments with separate account namespaces, so the builder has a
 * distinct account index on each.
 */
export type BuilderNetwork = 'mainnet' | 'testnet' | 'robinhood' | 'robinhood-testnet';

export interface BuilderAccount {
  /** Integrator account index on this network (0 = no builder registered). */
  readonly accountIndex: number;
  /** Human label for logs and the disclosure banner. */
  readonly label: string;
}

/**
 * The SDK builder's integrator accounts, per venue.
 *
 * These are the maintainer's accounts. If you fork this SDK for your own desk,
 * replace them with your own integrator indexes AND update
 * `REGISTRY_CHECKSUM` (the error message tells you the value to use), or the
 * integrity check will refuse to start.
 */
export const BUILDER_ACCOUNTS: Readonly<Record<BuilderNetwork, BuilderAccount>> = Object.freeze({
  mainnet: Object.freeze({ accountIndex: 692603, label: 'lighter-ts-sdk (Core)' }),
  testnet: Object.freeze({ accountIndex: 0, label: 'lighter-ts-sdk (Core testnet - none)' }),
  robinhood: Object.freeze({ accountIndex: 76, label: 'lighter-ts-sdk (Robinhood)' }),
  'robinhood-testnet': Object.freeze({ accountIndex: 0, label: 'lighter-ts-sdk (RH testnet - none)' }),
});

/**
 * Default fee split, in millionths of notional.
 *
 * maker 0.5 bps / taker 2 bps — deliberately small so MM quotes stay viable.
 * A market maker's gross edge is typically 5-20 bps, so 0.5 bps of maker fee
 * is a few percent of edge rather than a material drag.
 */
export const DEFAULT_MAKER_FEE_MILLIONTHS = 50; // 0.5 bps
export const DEFAULT_TAKER_FEE_MILLIONTHS = 200; // 2.0 bps

/**
 * Hard ceilings this SDK will never exceed, whatever the config says.
 *
 * These protect the USER, not the builder: a typo in `INTEGRATOR_TAKER_FEE`
 * (20000 instead of 200) would otherwise sign orders paying 200 bps.
 * `assertFeeWithinCap()` refuses rather than silently clamping, so a bad
 * config is visible instead of quietly re-priced.
 *
 * The protocol's own systemConfig caps are higher (Core perps 1000 = 10 bps,
 * RH 10000 = 100 bps); these are the SDK's stricter self-imposed limits.
 */
export const MAX_MAKER_FEE_MILLIONTHS = 200; // 2 bps
export const MAX_TAKER_FEE_MILLIONTHS = 1000; // 10 bps

/**
 * Checksum over the registry + fee policy. Recomputed by
 * `computeRegistryChecksum()`; a mismatch means the constants above were
 * edited without updating this value.
 */
export const REGISTRY_CHECKSUM = 'c74d3b19';

/**
 * Deterministic FNV-1a over the registry's material values. Not a security
 * primitive — a tripwire against partial edits and bad merges.
 */
export function computeRegistryChecksum(): string {
  const material = [
    ...Object.entries(BUILDER_ACCOUNTS)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([net, acct]) => `${net}:${acct.accountIndex}`),
    `maker:${DEFAULT_MAKER_FEE_MILLIONTHS}`,
    `taker:${DEFAULT_TAKER_FEE_MILLIONTHS}`,
    `maxMaker:${MAX_MAKER_FEE_MILLIONTHS}`,
    `maxTaker:${MAX_TAKER_FEE_MILLIONTHS}`,
  ].join('|');

  let hash = 0x811c9dc5;
  for (let i = 0; i < material.length; i++) {
    hash ^= material.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, '0');
}

/** Thrown when the registry constants and the checksum disagree. */
export class BuilderRegistryIntegrityError extends Error {
  constructor(expected: string, actual: string) {
    super(
      `Builder registry integrity check FAILED (expected checksum ${expected}, computed ${actual}).\n` +
        `\n` +
        `The builder account indexes or fee policy in\n` +
        `src/attribution/builder-registry.ts were changed without updating\n` +
        `REGISTRY_CHECKSUM. This is a hard error because trading with a\n` +
        `half-edited attribution config can reference an integrator that was\n` +
        `never approved on-chain — the sequencer rejects those orders and every\n` +
        `quote fails until it is fixed.\n` +
        `\n` +
        `If the edit was intentional (you forked this SDK for your own desk):\n` +
        `  1. set REGISTRY_CHECKSUM = '${actual}'\n` +
        `  2. re-run: npx jest tests/builder-attribution.test.ts\n` +
        `\n` +
        `If you only want to stop paying the SDK builder, do not edit this file —\n` +
        `set BUILDER_ATTRIBUTION=off (or INTEGRATOR_ACCOUNT_INDEX=0) in your .env.`,
    );
    this.name = 'BuilderRegistryIntegrityError';
  }
}

/**
 * Verify the registry has not been partially edited. Called from the
 * attribution resolver, the strategy constructor, and the order signer.
 */
export function verifyRegistryIntegrity(): void {
  const actual = computeRegistryChecksum();
  if (actual !== REGISTRY_CHECKSUM) {
    throw new BuilderRegistryIntegrityError(REGISTRY_CHECKSUM, actual);
  }
}

/** Map loose venue aliases ('core', 'rh', ...) onto registry keys. */
export function normalizeNetwork(network: string): BuilderNetwork | undefined {
  switch (String(network).toLowerCase()) {
    case 'mainnet':
    case 'core':
      return 'mainnet';
    case 'testnet':
      return 'testnet';
    case 'robinhood':
    case 'rh':
      return 'robinhood';
    case 'robinhood-testnet':
    case 'rh-testnet':
      return 'robinhood-testnet';
    default:
      return undefined;
  }
}

/** Builder account for a network, or undefined when none is registered. */
export function builderAccountFor(network: string): BuilderAccount | undefined {
  const key = normalizeNetwork(network);
  if (!key) return undefined;
  const acct = BUILDER_ACCOUNTS[key];
  return acct && acct.accountIndex > 0 ? acct : undefined;
}
